---
alias: Goodmorning
description: Goodmorning mode
id: a2ca80ee-163c-4a3f-86e7-69c9a370f9bc
mode: single
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: GOOD_MORNING
action:
  - choose:
        # IF mode is cool
      - conditions:
          - condition: state
            entity_id:
              - climate.upstairs_thermostat_mode
              - climate.downstairs_thermostat_mode
            state: cool
        # THEN set climate to cooling temps
        sequence:
          - service: climate.set_temperature
            data:
              entity_id: climate.upstairs_thermostat_mode
              temperature: 76
          - service: climate.set_temperature
            data:
              entity_id: climate.downstairs_thermostat_mode
              temperature: 74

        # IF AC is set to heat
      - conditions:
          - condition: state
            entity_id:
              - climate.upstairs_thermostat_mode
              - climate.downstairs_thermostat_mode
            state: heat
        # THEN set temperature 
        sequence:
          - service: climate.set_temperature
            data:
              entity_id:
                - climate.upstairs_thermostat_mode
                - climate.downstairs_thermostat_mode
              temperature: 72

  - service: notify.everyone
    data:
      title: "Mode"
      message: "🌅 Good Morning! The Home is set."
      data:
        push:
          thread-id: "mode"