---
alias: Goodnight Mode
description: Shutdown the house and set the house to sleep mode
id: 73cf8354-038f-4da1-a74a-0f710da0b403
mode: single
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: GOOD_NIGHT
  - platform: state
    entity_id:
      - sensor.master_bedroom_button_l_click
      - sensor.master_bedroom_button_r_click
    to: 'long'
  - platform: template
    value_template: "{{ is_state( 'alarm_control_panel.alarm', 'armed_home') and is_state( 'input_boolean.guest_mode', 'on') }}"
condition:
    # This is so that I don't run this accidentally when house is in away mode
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: disarmed
action:
  - service: light.turn_off
    entity_id: light.all_lights

  - service: lock.lock
    entity_id: lock.front_door

  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.alarm 

  - choose:
        # IF the AC is set to Cool (i.e. it is summer / hotter weather)
      - conditions:
          - condition: state
            entity_id:
              - climate.upstairs_thermostat_mode
              - climate.downstairs_thermostat_mode
            state: cool
        # THEN set the target temperature to our max high temp to keep the home nice and cool at night
        sequence:
          - service: climate.set_temperature
            data:
              entity_id:
                - climate.downstairs_thermostat_mode
                - climate.upstairs_thermostat_mode
              temperature: 68
              
        # IF the AC is set to heat (i.e. it is probably winter)
      - conditions:
          - condition: state
            entity_id:
              - climate.upstairs_thermostat_mode
              - climate.downstairs_thermostat_mode
            state: heat
        # THEN set the target temperature to a low threshold so that the home can naturally cool down
        sequence:
          - service: climate.set_temperature
            data:
              entity_id:
                - climate.upstairs_thermostat_mode
                - climate.downstairs_thermostat_mode
              temperature: 65

  - service: media_player.volume_set
    data:
      entity_id: media_player.master_bedroom_echo
      volume_level: 0.5

  - delay: 2

  - service: notify.alexa_media_master_bedroom_echo
    data:
      message: "<amazon:effect name='whispered'>Have a good night and sweet dreams.</amazon:effect>"
      data:
        type: tts

  - service: notify.everyone
    data:
      title: "Mode"
      message: "🌃 Good night and sweet dreams!"
      data:
        push:
          thread-id: "mode"