---
alias: Vacation Mode
description: Set house to vacation mode
id: 8dff5f96-ae9f-494f-acc5-ac024fd53eff
mode: single
trigger:
  - entity_id: input_boolean.vacation_mode
    platform: state
    to: 'on'
action:
  - service: climate.turn_off
    entity_id:
    - climate.upstairs
    - climate.downstairs
  - service: light.turn_off
    entity_id: all
  - service: lock.lock
    entity_id: all
  - service: notify.everyone
    data:
      title: "Mode"
      message: "✈️ Have a fun trip!"
      data:
        push:
          thread-id: "mode"