---
alias: Doorbell Motion Notify
description: Notify when there is motion in the front door
id: aec49088-ade8-4e24-8830-0360c159de97
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.front_door_motion
    to: 'on'
condition: []
action:
  - service: notify.everyone
    data:
      title: "Front Door"
      message: "🚶 There is motion at the front door"
      data:
        push:
          thread-id: "front-door"