---
alias: Door Lock Left Unlocked
description: >-
  Send a TTS when the front door is left unlocked
  Using trigger variables from release 2022.4
id: 0c4b6206-7cf1-4327-a087-d3bdacc7f9aa
mode: single
trigger:
  - platform: state
    entity_id: lock.front_door
    to: 'unlocked'
    for:
      minutes: 30
    variables:
      door_name: "front door"
  - platform: state
    entity_id: lock.back_door
    to: 'unlocked'
    for:
      minutes: 30
    variables:
      door_name: "back door"
condition:
  - condition: numeric_state
    entity_id: zone.home
    above: 0
action:
  - service: notify.everyone
    data:
      message: "You left the {{door_name}} unlocked for greater than 30mins"
      title: "Door left unlocked"
