---
alias: Living Room Lamps Sunset
description: >-
  Turn on living room lamps 15mins before Sunset
id: e582ffaa-f400-4d5b-858e-fcb6eb40ee3a
mode: single
trigger:
  - platform: sun
    event: sunset
    offset: "-00:15:00"
condition:
  - alias: "Vacation is off"
    condition: state
    entity_id: "input_boolean.vacation_mode"
    state: "off"
  - alias: "Alarm is disarmed"
    condition: state
    entity_id: "alarm_control_panel.alarm"
    state: "disarmed"
action:
  - service: light.turn_on
    target:
      entity_id: "light.living_room_lamps"
    data:
      transition: 30
      brightness_pct: 100
