path: settings
title: settings
icon: mdi:cog
cards:
- type: entities
  title: Visitors
  show_header_toggle: false
  entities:
    - entity: sensor.weatherstem_temperature
    - entity: sensor.dark_sky_daytime_high_apparent_temperature_0d
    - entity: sensor.nws_temperature_high_today
    - entity: sensor.weatherstem_temperature_high