---
alias: Garage notification
description: Garage open / close notification
id: 2dd4be68-7fa8-47c5-9f6b-527967022edb
mode: single
trigger:
  - platform: state
    entity_id: "binary_sensor.garage"
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: "binary_sensor.garage"
    from: 'on'
    to: 'off'
variables:
  message: >-
    {% if is_state('binary_sensor.garage', 'off') %}
    Garage door closed
    {% else %}
    Garage door opened
    {% endif %}
condition:
  - condition: numeric_state
    entity_id: "sensor.home_assistant_uptime"
    above: 3
action:
  - service: notify.everyone
    data:
      title: "Garage"
      message: "{{ message }}"
      data:
        push:
          thread-id: "garage"