---
alias: Kitchen Blinds Sunrise
description: >-
  Open kitchen blinds at Sunrise
id: ce54d8a7-94d0-46ac-9670-b5bd369d2257
mode: single
trigger:
  - platform: sun
    event: sunrise
    offset: "-00:15:00"
condition:
  - alias: "Vacation is off"
    condition: state
    entity_id: input_boolean.vacation_mode
    state: "off"
action:
  - service: cover.open_cover
    target:
      entity_id:
        - cover.kitchen_blind_l
        - cover.kitchen_blind_r