- platform: group
  name: Living Room lamps
  entities:
    - light.living_room_floor_lamp_l
    - light.living_room_floor_lamp_r
    - light.living_room_lamp

- platform: group
  name: Master Bedroom lamps
  entities:
    - light.master_bedroom_lamp_l
    - light.master_bedroom_lamp_r