- platform: group
  name: Living Room lamps
  entities:
    - light.living_room_floor_lamp_l_light
    - light.living_room_floor_lamp_r_light
    - light.living_room_lamp_light

- platform: group
  name: Master Bedroom lamps
  entities:
    - light.master_bedroom_lamp_l_light
    - light.master_bedroom_lamp_r_light